---
anchors:
  thresholds-operstate: &thresholds-operstate
    - color: "#FF3154" # red
      level: 0
    - color: "#4BDD33" # green
      level: 1
  thresholds-traffic: &thresholds-traffic
    - color: "#bec8d2" # grey
      level: 0
    - color: "#4BDD33" # green
      level: 199999
    - color: "#FFFF00" # yellow
      level: 500000
    - color: "#FF8000" # orange
      level: 1000000
    - color: "#FF3154" # red
      level: 5000000
  label-config: &label-config
    separator: replace
    units: bps
    decimalPoints: 1
    valueMappings:
      - valueMax: 199999
        text: ​
      - valueMin: 200000
cellIdPreamble: cell-
cells:
  spine1:e1-1:leaf1:e1-49:
    dataRef: oper-state:spine1:e1-1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine1:e1-1:leaf1:e1-49:
    dataRef: spine1:e1-1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine1:e1-2:leaf2:e1-49:
    dataRef: oper-state:spine1:e1-2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine1:e1-2:leaf2:e1-49:
    dataRef: spine1:e1-2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine2:e1-1:leaf1:e1-50:
    dataRef: oper-state:spine2:e1-1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine2:e1-1:leaf1:e1-50:
    dataRef: spine2:e1-1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  spine2:e1-2:leaf2:e1-50:
    dataRef: oper-state:spine2:e1-2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:spine2:e1-2:leaf2:e1-50:
    dataRef: spine2:e1-2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  leaf1:e1-49:spine1:e1-1:
    dataRef: oper-state:leaf1:e1-49
    fillColor:
      thresholds: *thresholds-operstate
  leaf1:e1-50:spine2:e1-1:
    dataRef: oper-state:leaf1:e1-50
    fillColor:
      thresholds: *thresholds-operstate
  leaf1:e1-1:client1:eth1:
    dataRef: oper-state:leaf1:e1-1
    fillColor:
      thresholds: *thresholds-operstate
  leaf2:e1-49:spine1:e1-2:
    dataRef: oper-state:leaf2:e1-49
    fillColor:
      thresholds: *thresholds-operstate
  leaf2:e1-50:spine2:e1-2:
    dataRef: oper-state:leaf2:e1-50
    fillColor:
      thresholds: *thresholds-operstate
  leaf2:e1-1:client2:eth1:
    dataRef: oper-state:leaf2:e1-1
    fillColor:
      thresholds: *thresholds-operstate
  client1:eth1:leaf1:e1-1:
    dataRef: oper-state:client1:eth1
    fillColor:
      thresholds: *thresholds-operstate
  client2:eth1:leaf2:e1-1:
    dataRef: oper-state:client2:eth1
    fillColor:
      thresholds: *thresholds-operstate
links:
  - source: spine1:e1-1
    target: leaf1:e1-49
    dataRef: oper-state:spine1:e1-1
    link_id: spine1:e1-1:leaf1:e1-49
    dataRef: spine1:e1-1:out
  - source: spine1:e1-2
    target: leaf2:e1-49
    dataRef: oper-state:spine1:e1-2
    link_id: spine1:e1-2:leaf2:e1-49
    dataRef: spine1:e1-2:out
  - source: spine2:e1-1
    target: leaf1:e1-50
    dataRef: oper-state:spine2:e1-1
    link_id: spine2:e1-1:leaf1:e1-50
    dataRef: spine2:e1-1:out
  - source: spine2:e1-2
    target: leaf2:e1-50
    dataRef: oper-state:spine2:e1-2
    link_id: spine2:e1-2:leaf2:e1-50
    dataRef: spine2:e1-2:out
  - source: leaf1:e1-1
    target: client1:eth1
    dataRef: oper-state:leaf1:e1-1
    link_id: leaf1:e1-1:client1:eth1
    dataRef: leaf1:e1-1:out
  - source: leaf2:e1-1
    target: client2:eth1
    dataRef: oper-state:leaf2:e1-1
    link_id: leaf2:e1-1:client2:eth1
    dataRef: leaf2:e1-1:out