# Ansible inventory created from ['/home/ubuntu/netlab_ceos/ceos.yaml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
all: {}
modules:
  hosts: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
eos:
  hosts:
    r1:
      ansible_host: clab-netlab_ceos-r1
      id: 1
    r2:
      ansible_host: clab-netlab_ceos-r2
      id: 2
